FROM python:3.11-slim

# Install mosquitto-clients for testing
RUN apt-get update && apt-get install -y mosquitto-clients

# Install Python dependencies
RUN pip install paho-mqtt

COPY publisher.py /publisher.py

CMD ["python", "/publisher.py"]
