FROM python:3.11-slim

RUN apt-get update && \
    apt-get install -y feh && \
    pip install pillow paho-mqtt

COPY viewer_mqtt.py /viewer_mqtt.py
COPY fonts/DSEG7Classic-Bold.ttf /fonts/DSEG7Classic-Bold.ttf

CMD ["python", "/viewer_mqtt.py"]
